### ISSUE TITLE
启动main.py报错

### ISSUE THREAD

**Issue by heyb130** [TheRamU/Fay#2]
python版本：3.8.7
系统：windows 7
按照文档，各个依赖库都按相应版本pip install成功
导入pycharm项目中，运行main.py 报错，麻烦作者大大，帮忙看一下问题，谢谢！

错误信息如下：
Traceback (most recent call last):
  File "D:\Python\Python38\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 27, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _speech_py_impl: 找不到指定的程序。

**Comment by xszyou** [comment]
1、pyaudio无安装成功的可能性会比较大，你写段简单的代码测试一下pyaudio：
import pyaudio
audio = pyaudio.PyAudio()
print(audio.get_device_count())

2、另外也请确定微软语音识别的key是否配置上。

**Comment by xszyou** [comment]
参考：https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/792
