### ISSUE TITLE
mac M1  pip install ./FunASR 安装报错

### ISSUE THREAD

**Issue by yangyuanwei** [TheRamU/Fay#37]
(base) yyw@yywdeMac-mini Fay % pip install ./FunASR
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing ./FunASR
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/yyw/Desktop/QuWan/AIProject/Fay/FunASR/setup.py", line 125, in <module>
          setup(
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/yyw/miniforge3/lib/python3.10/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/Users/yyw/Desktop/QuWan/AIProject/Fay/FunASR/.eggs/numpy-1.21.3-py3.10-macosx-11.0-arm64.egg/numpy-1.21.3.dist-info' -> '/Users/yyw/Desktop/QuWan/AIProject/Fay/FunASR/.eggs/numpy-1.21.3-py3.10-macosx-11.0-arm64.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kangkangding** [comment]
Has the problem been solved? I have encountered the same problem
