### ISSUE TITLE
python main.py 报错，qt打开后空白几秒然后就关闭了，控制台信息如下

### ISSUE THREAD

**Issue by shenshiqiSSQ** [TheRamU/Fay#41]
C:\Users\淇淇\AppData\Local\Programs\Python\Python39\python.exe C:/Users/淇淇/Desktop/GPTapi/数字人/Fay/main.py
pygame 2.1.3 (SDL 2.0.22, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\淇淇\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 434, in select
Traceback (most recent call last):
  File "C:\Users\淇淇\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 434, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001BF935AC930> still has pending operation at deallocation, the process may crash
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001BF935AC9C0> still has pending operation at deallocation, the process may crash

进程已结束,退出代码-1073740791 (0xC0000409)

**Comment by Albert337** [comment]
i create a virtual environment to run the code ,and meet the error:
 "libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Aborted (core dumped)
" ,how to fix it?Is there any suggestion?Thanks!

**Comment by smartswordsman** [comment]
你好，请问下这个问题有解决吗？ @Albert337

**Comment by shenshiqiSSQ** [comment]
安装环境有问题，需要装qt需要环境，并且在win cmd可以执行，其中有中文路径不行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月26日(星期三) 下午3:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TheRamU/Fay] python main.py 报错，qt打开后空白几秒然后就关闭了，控制台信息如下 (Issue #41)





 
你好，请问下这个问题有解决吗？ @Albert337

**Comment by HuaYuXiao** [comment]
> i create a virtual environment to run the code ,and meet the error: "libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri) libGL error: failed to load driver: iris libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri) libGL error: failed to load driver: iris libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri) libGL error: failed to load driver: swrast WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed. QGLXContext: Failed to create dummy context Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlagsQSurfaceFormat::FormatOption(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile QSurfaceFormat::NoProfile) Aborted (core dumped) " ,how to fix it?Is there any suggestion?Thanks!

Have you ever installed the required libs? Just as the messages said.
