### ISSUE TITLE
同样用openai apikey，助手分支运行报错，售卖员分支正常

### ISSUE THREAD

**Issue by ChaocunChen** [TheRamU/Fay#94]
助手分支运行 python main.py 报错 
Retrying langchain_community.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))).
但是售卖员分支运行是正常的，同样用openai的aip key

**Comment by ChaocunChen** [comment]
完整报错信息
C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
pygame 2.1.3 (SDL 2.0.22, Python 3.8.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
Retrying langchain_community.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))).
Traceback (most recent call last):
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\connectionpool.py", line 712, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\connectionpool.py", line 1012, in _prepare_proxy
    conn.connect()
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "C:\Users\soft\anaconda3\envs\langchain\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\connectionpool.py", line 827, in urlopen
    return self.urlopen(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\connectionpool.py", line 827, in urlopen
    return self.urlopen(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\openai\api_requestor.py", line 606, in request_raw
    result = _thread_context.session.request(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\main.py", line 10, in <module>
    from gui import flask_server
  File "C:\Users\soft\PycharmProjects\fay-assistant\gui\flask_server.py", line 9, in <module>
    import fay_booter
  File "C:\Users\soft\PycharmProjects\fay-assistant\fay_booter.py", line 5, in <module>
    from core.fay_core import FeiFei
  File "C:\Users\soft\PycharmProjects\fay-assistant\core\fay_core.py", line 28, in <module>
    from agent import agent_service
  File "C:\Users\soft\PycharmProjects\fay-assistant\agent\agent_service.py", line 9, in <module>
    agent = FayAgentCore()
  File "C:\Users\soft\PycharmProjects\fay-assistant\agent\fay_agent.py", line 52, in __init__
    memory.save_context({"input": "我的基本信息是?"}, {"output": attr_info})
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain\memory\vectorstore.py", line 74, in save_context
    self.retriever.add_documents(documents)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain_core\vectorstores.py", line 696, in add_documents
    return self.vectorstore.add_documents(documents, **kwargs)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain_core\vectorstores.py", line 122, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain_community\vectorstores\faiss.py", line 226, in add_texts
    embeddings = self._embed_documents(texts)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain_community\vectorstores\faiss.py", line 138, in _embed_documents
    return self.embedding_function.embed_documents(texts)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain_community\embeddings\openai.py", line 667, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain_community\embeddings\openai.py", line 493, in _get_len_safe_embeddings
    response = embed_with_retry(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain_community\embeddings\openai.py", line 123, in embed_with_retry
    return _embed_with_retry(**kwargs)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "C:\Users\soft\anaconda3\envs\langchain\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "C:\Users\soft\anaconda3\envs\langchain\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\langchain_community\embeddings\openai.py", line 120, in _embed_with_retry
    response = embeddings.client.create(**kwargs)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\openai\api_requestor.py", line 289, in request
    result = self.request_raw(
  File "C:\Users\soft\anaconda3\envs\langchain\lib\site-packages\openai\api_requestor.py", line 619, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/embeddings (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))
大佬帮忙看下
